### ISSUE TITLE
如何让两张图片在各自的div内移动

### ISSUE THREAD

**Issue by laker55555** [NoticeVengus/ZoomMarker#11]
如果使用了limit功能，图片的拖动感觉就会有问题。不使用的话，两张图片会在更外层的div内移动，并且能够叠加在一起

**Comment by laker55555** [comment]
![11](https://user-images.githubusercontent.com/51220558/58678899-eeb85600-8393-11e9-9f49-339119b42782.gif)

**Comment by yeye0922** [comment]
你是不希望这两张图片重叠在一起吗？

**Comment by laker55555** [comment]
是的，就是想只在各自的范围内进行移动，缩放

**Comment by yeye0922** [comment]
已经更新了版本，修改了锁边情况下的缩放逻辑
在一定范围内移动缩放可以参考以下例子：
https://yeye0922.github.io/ZoomMarker/index_half.html
