### ISSUE TITLE
我想问一下,初始打开的时候,标点不在图片上,一定要鼠标滚动才显示到正确的位置,是什么原因

### ISSUE THREAD

**Issue by newbeginning12** [NoticeVengus/ZoomMarker#12]
![1562416168(1)](https://user-images.githubusercontent.com/52600707/60756160-cd9af300-a02c-11e9-8544-f64934e8f95e.jpg)

**Comment by yeye0922** [comment]
是什么浏览器？你是在初始化的时候传入标记点坐标的吗

**Comment by newbeginning12** [comment]
是的，初始化在markers里传入自定义数组

**Comment by newbeginning12** [comment]
360浏览器

**Comment by yeye0922** [comment]
在360浏览器上没有复现该问题，看看控制台有什么输出吧

**Comment by newbeginning12** [comment]
![1564039386(1)](https://user-images.githubusercontent.com/52600707/61854362-7d5ad680-aef0-11e9-9150-dbc0ae3687c7.jpg)
![1564039222(1)](https://user-images.githubusercontent.com/52600707/61854365-7df36d00-aef0-11e9-9560-20b4e9d29db0.jpg)

**Comment by newbeginning12** [comment]
可以对每个标点添加不同的文字信息窗吗？

**Comment by yeye0922** [comment]
可以，使用添加标记点的方法，传入dialog样式即可
