### ISSUE TITLE
如何在Vue中使用

### ISSUE THREAD

**Issue by renjietan** [NoticeVengus/ZoomMarker#14]
请问大佬，如何在VUE中使用呢   可以写个readme.md 介绍下么  感激不尽

**Comment by NoticeVengus** [comment]
插件就是是用jquery使用的，可以看看网上的vue使用jquery的教程，我找了一篇，希望对你有帮助：
[Vue中正确使用jQuery的方法](https://www.cnblogs.com/fps2tao/p/9565570.html)
