### ISSUE TITLE
vue里面路由跳转出问题

### ISSUE THREAD

**Issue by hajiwa** [NoticeVengus/ZoomMarker#24]
vue里面路由跳转后再返回就显示不出图片，调用zoomMarker_ResetImage，zoomMarker_LoadImage 都没反应

**Comment by hajiwa** [comment]
为了赶时间在源码里改了

**Comment by LiuYnag** [comment]
> vue里面路由跳转后再返回就显示不出图片，调用zoomMarker_ResetImage，zoomMarker_LoadImage 都没反应



> 为了赶时间在源码里改了

兄弟，还有源码没，被同样问题折磨的不行
